### ISSUE TITLE
Possible bug in DecayCell

### ISSUE THREAD

**Issue by fmartiescofet** [joeloskarsson/tgnn4i#1]
In the DecayCell class, when computing `h_tilde` [in line 134](https://github.com/joeloskarsson/tgnn4i/blob/f91d04910912056e5d51e7fa0260d26c7e57f21b/models/decay_cell.py#L134C22-L134C22) `W_xr` is used. Shouldn't this be `Wx_h` as defined in equation 10c) in the paper?

The same thing happens [in line 146](https://github.com/joeloskarsson/tgnn4i/blob/f91d04910912056e5d51e7fa0260d26c7e57f21b/models/decay_cell.py#L146C38-L146C38) for `hd_tilde`.

Francesc

**Comment by joeloskarsson** [comment]
Hi, thanks for pointing this out. This basically entails a form of parameter sharing between v_{i,2} and v_{i,3} (and similar for v_{i,5} and v_{i,6}). Not sure what the effect of this is, but will investigate. In the meantime, if you want a more flexible model you can replace it with `Wx_h` as you describe.

**Comment by joeloskarsson** [comment]
I made this change and ran through the experiments again. The impact of this is very minor in practice. The metric values in our experiments hardly change at all, or within the standard deviation. 

Still, I'll change this as I think it is nicer if it is more in line with the equation in the paper. The results should reproduce without issues either way.
